package ovcharka.conceptservice;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.event.EventListener;
import ovcharka.conceptservice.domain.Concept;
import ovcharka.conceptservice.service.ConceptService;

import java.util.List;

@Configuration
public class Initializer {

    private final ConceptService conceptService;

    @Autowired
    public Initializer(ConceptService conceptService) {
        this.conceptService = conceptService;
    }

    @EventListener(ApplicationReadyEvent.class)
    public void init(ApplicationReadyEvent event) {
        conceptService.updateConcepts(List.of(
                Concept.of("bit", "the amount of information in a system having two equiprobable states", 4),
                Concept.of("buffer", "a part of RAM used for temporary storage of data that is waiting to be sent to a device", 3),
                Concept.of("byte", "a sequence of 8 bits processed as a single unit of information", 4),
                Concept.of("hardware", "the mechanical, magnetic, electronic, and electrical components making up a computer system", 3),
                Concept.of("memory", "the computer hardware integrated circuits that store information for immediate use in a computer", 5),
                Concept.of("network", "a system of interconnected electronic components or circuits", 2),
                Concept.of("packet", "a message or message fragment", 5),
                Concept.of("protocol", "rules determining the format and transmission of data", 4),
                Concept.of("software", "a collection of data or computer instructions that tell the computer how to work", 3),
                Concept.of("object", "a value in memory referenced by an identifier", 2),
                Concept.of("variable", "a quantity that can assume any of a set of values", 3),
                Concept.of("algorithm", "a precise rule specifying how to solve some problem", 4),
                Concept.of("database", "an organized body of related information", 4),
                Concept.of("bug", "a fault or defect in a computer program, system, or machine", 4),
                Concept.of("C", "a general-purpose programing language closely associated with the UNIX operatin system", 5),
                Concept.of("Java", "a platform-independent object-oriented programming language", 5),
                Concept.of("compiler", "a program that decodes instructions written in a higher order language and produces an assembly language program", 5),
                Concept.of("translator", "a program that translates one programming language into another", 5),
                Concept.of("code", "the symbolic arrangement of data or instructions in a computer program", 4),
                Concept.of("map", "a mathematical relation such that each element of a given set is associated with an element of another set", 3),
                Concept.of("stack", "a storage device that handles data so that the next item to be retrieved is the item most recently stored", 5),
                Concept.of("computer", "a machine for performing calculations automatically", 2),
                Concept.of("interface", "computer circuit consisting of the hardware and associated circuitry that links one device with another", 2),
                Concept.of("Linux", "an open-source version of the UNIX operating system", 3),
                Concept.of("instruction", "a line of code written as part of a computer program", 3),
                Concept.of("multiprocessing", "simultaneous processing by two or more processing units", 2),
                Concept.of("source code", "program instructions translated by a compiler or interpreter or assembler into the object code", 4),
                Concept.of("recursion", "an expression such that each term is generated by repeating a particular mathematical operation", 4),
                Concept.of("register", "memory device that is the part of computer memory that has an address and that is used to hold information", 3),
                Concept.of("operating system", "software that controls the execution of computer programs and may provide various services", 4),
                Concept.of("computing", "the branch of engineering science that studies (with the aid of computers) computable processes and structures", 5),
                Concept.of("cipher", "a secret method of writing", 2))
        );
    }
}
